apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: default
  hostPath:
    path: {llama_model_path}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
  volumeName: llama-pv
