
PARAM_OPENAI_KEY = 'openai_key'
PARAM_LLAMA_CONTEXT_SIZE = 'llama_context_size'
PARAM_LLAMA_MODEL = 'llama_model'

ENV_LOG_LEVEL = "LOG_LEVEL"
ENV_OPENAI_API_KEY = "OPENAI_API_KEY"
ENV_LLAMA_MODEL_FILE = "LLAMA_MODEL_FILE"
ENV_LLAMA_CONTEXT_SIZE = "LLAMA_CONTEXT_SIZE"

MODEL_OPENAI = "openai"
MODEL_LLAMA = "llama"

MODEL_CONTEXT_SIZE = 4096

CHAT_ROLE_USER = "user"
CHAT_ROLE_ASSISTANT = "assistant"
CHAT_ROLE_SYSTEM = "system"

CHAT_PREFIX_ASSISTANT = "Assistant"
CHAT_PREFIX_USER = "Human"

CHAT_COMPLETION_CHUNK = "chat.completion.chunk"
CHAT_COMPLETION = "chat.completion"

CHAT_STREAM_END = "[DONE]"

CHAT_CHUNK_START = "data: "
